### ISSUE TITLE
possible bug: Ingress route via Traefik - subpath issue

### ISSUE THREAD

**Issue by mihaigalos** [iv-org/invidious-helm-chart#4]
I'm using Traefik to route to the inviduous deployment using:

<details><summary>values.yaml</summary>
<p>

```yaml
  image:
    tag: latest-arm64
  ingress:
    enabled: true
    className: traefik
    hosts:
    - host: cloud.galos.one
      paths:
        - path: /inv
          pathType: Prefix
```

</p>
</details> 

This generates the following - so far so good:

<details><summary>ingress.yaml</summary>
<p>

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: '2024-09-10T19:38:46Z'
  generation: 2
  labels:
    app.kubernetes.io/instance: invidious
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: invidious
    app.kubernetes.io/version: v2.20240427
    helm.sh/chart: invidious-2.0.4
  name: invidious
  namespace: invidious
  resourceVersion: '7226'
  uid: 58f2a708-c81e-4b8d-a0f2-741cb2ef3f69
spec:
  ingressClassName: traefik
  rules:
    - host: cloud.galos.one
      http:
        paths:
          - backend:
              service:
                name: invidious
                port:
                  number: 3000
            path: /inv
            pathType: Prefix
status:
  loadBalancer:
    ingress:
      - ip: 172.18.0.2
      - ip: 172.18.0.3
```

</p>
</details> 

But seems the full routing doesn't work, since the app reaches out to / and that is again under Traefik control.
Instead, if I interpret the logs correctly, it should rech out to /inv/internally_used_URL/

So I should be able to somehow specify a base_url in values - or consume the one already specified.

<details><summary>logs</summary>
<p>

```bash
curl -v https://cloud.galos.one/inv/
*   Trying 192.168.1.86:443...
* Connected to cloud.galos.one (192.168.1.86) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=cloud.galos.one
*  start date: Sep 10 19:05:11 2024 GMT
*  expire date: Dec  9 19:05:10 2024 GMT
*  subjectAltName: host "cloud.galos.one" matched cert's "cloud.galos.one"
*  issuer: C=US; O=Let's Encrypt; CN=R10
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x5599b44cc0)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /inv/ HTTP/2
> Host: cloud.galos.one
> user-agent: curl/7.81.0
> accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 302
< content-type: text/html
< location: /
< x-frame-options: sameorigin
< date: Tue, 10 Sep 2024 20:35:53 GMT
<
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection #0 to host cloud.galos.one left intact
```

</p>
</details>

**Comment by perennialtech** [comment]
Maybe specifying something like `values.config.domain: cloud.galos.one/inv` could resolve the issue?

However, Invidious isn't designed to be served under a URI path on a domain shared with other services AFAIK, and should hosted on its separate domain (for example, `invidious.example.com` or `invidious.subdomain.example.com`).

**Comment by mihaigalos** [comment]
Setting the `values.config.domain` didn't work.
Invidious is running in a k3s cluster on a single node. So using a separate domain would require a new host (different DNS A-Record), or a separate k3s instance/cluster.

I see projects like Prometheus (`.server.baseURL`) and Grafana (`.grafana.ini.server.root_url`) having options to configure the app to make it fully compliant with routing through ingresses.

Thank you for this app, and your time invested in it.

**Comment by mihaigalos** [comment]
I tried hosting it in / using:
```diff
    ingress:
      enabled: true
      className: traefik
      hosts:
      - host: cloud.galos.one
        paths:
-         - path: /inv
+         - path: /
            pathType: Prefix
    config:
-      domain: ""
+      domain: "cloud.galos.one"
```

This loads up the UI nicely, I can even search. When clicking on a video, I get an error.
It seems it's a classic, there are many issues like this:

Title: `relation "videos" does not exist (PQ::PQError)`
Date: `2024-09-11T20:15:56Z`
Route: `/watch?v=FlsBnDqbNUg`
Version: `2024.08.26-4782a67 @ (HEAD detached at v2.20240825.2)`

<details>
<summary>Backtrace</summary>
<p>
   
```
relation "videos" does not exist (PQ::PQError)
  from lib/pg/src/pq/connection.cr:202:22 in 'handle_error'
  from lib/pg/src/pq/connection.cr:225:65 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:415:59 in 'perform_query'
  from lib/db/src/db/statement.cr:93:9 in 'query:args'
  from lib/db/src/db/query_methods.cr:146:9 in 'select'
  from src/invidious/videos.cr:352:15 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:32:7 in 'call_next'
  from /usr/lib/crystal/core/string.cr:3075:20 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:30:7 in 'call'
  from /usr/lib/crystal/core/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

I cannot make sense of it in this context. Any thoughts?

**Comment by mihaigalos** [comment]
ChatGPT seems to think "videos" is a missing db table:
```
Q: why does invidious throw this error?

    2024-09-12 18:49:54 UTC [error] get_video: XuSQU5Grv1g : relation “videos” does not exist

The error indicates that Invidious is trying to access a database table named “videos,” but the table does not exist. This could be due to an issue with the database setup, such as:

    The database schema hasn’t been properly initialized or migrated.
    There’s an incomplete or failed installation process.
    The database connection details could be incorrect or misconfigured.
```

**Comment by JuniorJPDJ** [comment]
> Invidious is running in a k3s cluster on a single node. So using a separate domain would require a new host (different DNS A-Record), or a separate k3s instance/cluster.

This is not true. You can point multiple domains to the same host and the same cluster. This is exactly how it should be done.

**Comment by mihaigalos** [comment]
> You can point multiple domains to the same host and the same cluster.

So you're saying host k3s and separately invidious, both on the same node, both on a different port.
The DNS A-Record is different but pointing to the same machine. Would work, but would need to specify port -> defeats the purpose of DNS resolution, since I don't want to remember the port.

Maybe you know of a better way.

The initial problem statement was how to host directly in the cluster, not outside (ingress through Traefik).

**Comment by JuniorJPDJ** [comment]
What? No.
You can point multiple A records with other domains to the same IP and let ingress controller (traefik in your case) handle HTTP routing based on domain. You don't need path prefix, you can handle everything on just domain names.

**Comment by JuniorJPDJ** [comment]
eg. change `cloud.galos.one` to `inv.cloud.galos.one` and add A record in your DNS to point to the same IP address as `cloud.galos.one`. It should just work after that changes.

**Comment by unixfox** [comment]
This is similar to what has been requested in https://github.com/iv-org/invidious/issues/2441.

Invidious does not support sub path that's it. Use a separate domain for invidious.

**Comment by mihaigalos** [comment]
> eg. change `cloud.galos.one` to `inv.cloud.galos.one` and add A record in your DNS to point to the same IP address as `cloud.galos.one`. It should just work after that changes.

Thanks a lot, that worked! 😄
