### ISSUE TITLE
hmac_key not defined in config

### ISSUE THREAD

**Issue by Hazerre** [iv-org/invidious-helm-chart#6]
Using this helm chart results in an error due to hmac_key not being defined in the config.

**Comment by unixfox** [comment]
I don't see the issue. Just define it then?

I guess we could add it as a comment in the values.yaml

**Comment by DeD1rk** [comment]
It would actually be really nice if the hmac_key can be provided in a separate secret, rather then directly through helm values. That way, the helm values file can be public

**Comment by unixfox** [comment]
@DeD1rk feel free to open a PR for that :)
